<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: isilin
 * Date: Sat, 26 May 2018 09:15:01 +0000
 */

$conf['title'] = 'simxu';
$conf['basedir'] = '/simxu';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = 1;

// end auto-generated content
