<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: isilin
 * Date: Wed, 30 May 2018 08:12:01 +0000
 */

$conf['title'] = 'simxu';
$conf['basedir'] = '/simxu';
$conf['cookiedir'] = '/';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
$conf['plugin']['translation']['translations'] = 'en fr';
$conf['plugin']['translation']['dropdown'] = 1;
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['translation']['redirectstart'] = 1;
$conf['plugin']['translation']['checkage'] = 1;
$conf['plugin']['translation']['about'] = 'translation:about';
$conf['plugin']['translation']['localabout'] = 1;
$conf['plugin']['translation']['copytrans'] = 1;

// end auto-generated content
