# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 25 May 2018 06:29:30 +0000
*               @ALL          1
*               @user         4
