<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: isilin
 * Date: Fri, 25 May 2018 08:47:02 +0000
 */

$conf['title'] = 'simnomce\'u';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
$conf['cookiedir'] = /; // to keep the same authentification cookie for all the farm.

$conf['plugin']['translation']['translations'] = 'en,fr';
$conf['plugin']['translation']['dropdown'] = 1;
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin'][translation']['redirectstart'] = 1;
$conf['plugin']['translation']['checkage'] = 1;
$conf['plugin']['translation']['about'] = 'translation:about';
$conf['plugin']['translation']['localabout'] = 1;
$conf['plugin']['translation']['display'] = 'langcode,name';

// end auto-generated content
