<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: isilin
 * Date: Fri, 25 May 2018 08:47:02 +0000
 */

$conf['title'] = 'simnomce\'u';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';

// end auto-generated content
