<?php
/*
 * Local plugin enable/disable settings
 * Auto-generated through plugin/extension manager
 *
 * Auto-generated by install script
 * Date: Fri, 25 May 2018 06:29:30 +0000
 */
$plugins['authldap'] = 0;
$plugins['authpdo'] = 0;
